USE restaurant_db; 
-- 1. VIEW THE MENU_ITEMS TABLE
SELECT * FROM MENU_ITEMS;

-- 2. FIND THE NUMBER OF ITEMS ON THE MENU
SELECT COUNT(*) FROM MENU_ITEMS;

-- 3. WHAT ARE THE LEAST AND MOST EXPENSIVE ITEMS ON THE MENU
SELECT * FROM MENU_ITEMS
ORDER BY price;

-- 4. HOW MANY ITALIAN DISHES ARE ON THE MENU?
SELECT COUNT(*)FROM MENU_ITEMS
WHERE CATEGORY = 'ITALIAN';

-- 5. WHAT ARE THE LEAST AND MOST EXPENIVE ITALIAN DISHES ON THE MENU?
SELECT * FROM MENU_ITEMS
WHERE CATEGORY = 'ITALIAN'
ORDER BY PRICE
DESC;

-- 6. HOW MANY DISHES IN EACH CATEGORY?
SELECT category, COUNT(MENU_ITEM_ID) AS Num_dishes
FROM menu_items
group by category;

-- 7. WHAT IS THE AVERAGE DISH PRICE WITHIN EACH CATEGORY?
SELECT category, avg(PRICE) AS avg_dishes
FROM menu_items
GROUP BY category;